/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.4.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = uri("https://repo.mreil.com/gradle-plugins-snapshots") }
    }
}

plugins { id("com.mreil.easy.settings") version "0.0.100-SNAPSHOT" }

easy {
    publish {
        enabled.set(true)
        toMavenStaging()
        toMavenCentral()
        mavenRepo(
            "mreilComGradlePluginsSnapshots",
            "https://repo.mreil.com/gradle-plugins-snapshots",
            true
        )
        mavenRepo(
            "sonatypeSnapshots",
            "https://central.sonatype.com/repository/maven-snapshots/",
            true
        )
    }
}

rootProject.name = "gradle-easy-plugin-new"
include("easy-plugin")
include("easy-plugin-core")
include("easy-contributor-api")
include("easy-contributor-support")
include("easy-test-support")
include("gradle-plugin-testutils")
include("gradle-plugin-utils")
include("contributor-plugins:publish:publish-plugin-api")
include("contributor-plugins:publish:publish-plugin")
include("contributor-plugins:publish:publish-test-plugin")
include("contributor-plugins:jvm-defaults:jvm-defaults-plugin")
include("contributor-plugins:jvm-defaults:jvm-defaults-test-plugin")
include("contributor-plugins:semver:semver-plugin-api")
include("contributor-plugins:semver:semver-plugin")
include("contributor-plugins:semver:semver-test-plugin")
include("contributor-plugins:codemeta:codemeta-plugin-api")
include("contributor-plugins:codemeta:codemeta-plugin")
include("contributor-plugins:codemeta:codemeta-test-plugin")
include("contributor-plugins:project-defaults:project-defaults-plugin-api")
include("contributor-plugins:project-defaults:project-defaults-plugin")
include("contributor-plugins:project-defaults:project-defaults-test-plugin")
