/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.4.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "gradle-easy-plugin-new"
include("easy-plugin")
include("easy-plugin-core")
include("gradle-plugin-tools")
include("gradle-plugin-tools-api")
include("test-fixtures")
include("contributor-plugins:publish-plugin")
include("contributor-plugins:jvm-defaults")
