package com.mreil.easy.publish.central

import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory
import com.fasterxml.jackson.dataformat.yaml.YAMLGenerator
import com.fasterxml.jackson.module.kotlin.registerKotlinModule

/**
 * JReleaser YAML model and rendering for Maven Central deployment.
 *
 * [GenerateJreleaserConfigTask] keeps the lazy `@Input` properties and maps them
 * to [Config] at execution time; tests construct it directly without a Project.
 */
internal object JreleaserYaml {
    /**
     * Resolved JReleaser config values (plain data, no Gradle types).
     */
    data class Config(
        val projectName: String,
        val projectVersion: String,
        val projectGroupId: String,
        val stagingDirs: List<String>,
        val mavenCentralUsername: String,
        val mavenCentralPassword: String,
        val nexusUrl: String? = null,
        val nexusUsername: String = "",
        val nexusPassword: String = "",
    )

    internal fun buildYaml(config: Config): String {
        val fullConfig =
            linkedMapOf(
                "project" to
                    linkedMapOf(
                        "name" to config.projectName,
                        "version" to config.projectVersion,
                        "languages" to
                            linkedMapOf(
                                // artifactId defaults to the project name; groupId is required
                                // (deployer namespaces and artifact matching default to it).
                                "java" to linkedMapOf("groupId" to config.projectGroupId),
                            ),
                    ),
                "deploy" to
                    linkedMapOf(
                        "maven" to
                            LinkedHashMap<String, Any>().also { maven ->
                                deployersFor(config).forEach { deployer ->
                                    maven[deployer.section] = mapOf(deployer.name to deployer.toMap())
                                }
                            },
                    ),
            )
        val yaml = yamlMapper.writeValueAsString(fullConfig)
        return "# Generated by EasyPublishPlugin — JReleaser config for Maven Central\n" + yaml
    }

    private val yamlMapper: ObjectMapper =
        ObjectMapper(
            YAMLFactory
                .builder()
                .enable(YAMLGenerator.Feature.MINIMIZE_QUOTES)
                .enable(YAMLGenerator.Feature.INDENT_ARRAYS)
                .enable(YAMLGenerator.Feature.INDENT_ARRAYS_WITH_INDICATOR)
                .disable(YAMLGenerator.Feature.WRITE_DOC_START_MARKER)
                .build(),
        ).registerKotlinModule()
}
