/*
 * This source file was generated by the Gradle 'init' task
 */
package com.mreil.easy

import org.gradle.api.Plugin
import org.gradle.api.Project
import kotlin.reflect.KClass

/** Project plugin that discovers and applies contributed plugins. */
class ProjectPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        val registry = getRegistry(project)
        registry.loadFromServiceLoader(javaClass.classLoader)
        if (project.extensions.findByName(EasyExtension.name) == null) {
            ExtensionRegistrar.createExtension(
                project,
                registry,
            )
        }
        project.plugins.withType(ProjectPlugin::class.java) {
            applyRegisteredPlugins(project, registry)
        }
    }

    private fun getRegistry(project: Project): PluginRegistryService =
        project.gradle.sharedServices
            .registerIfAbsent(
                PluginRegistry.NAME,
                PluginRegistryService::class.java,
            ).get()

    private fun applyRegisteredPlugins(
        project: Project,
        registry: PluginRegistryService,
    ) {
        val allProjects = orderedAllProjects(project)
        registry.getProjectPlugins().forEach { kclass ->
            val targets = targetsFor(kclass, project, allProjects, registry)
            targets.forEach { target ->
                try {
                    target.pluginManager.apply(kclass.java)
                } catch (_: Exception) {
                }
            }
        }
    }

    private fun orderedAllProjects(project: Project): List<Project> {
        val root = project.gradle.rootProject
        return listOf(root) + root.subprojects.sortedBy { it.path }
    }

    private fun targetsFor(
        kclass: KClass<out Plugin<Project>>,
        project: Project,
        allProjects: List<Project>,
        registry: PluginRegistryService,
    ): List<Project> {
        @Suppress("UNCHECKED_CAST")
        val contributor = registry.getContributorFor(kclass as KClass<out Plugin<*>>)
        val toSubprojects =
            contributor?.let {
                it::class.java.isAnnotationPresent(ApplyToSubprojects::class.java)
            } ?: false
        return if (toSubprojects) allProjects else listOf(project)
    }
}
