package com.mreil.easy.publish

import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory
import com.fasterxml.jackson.dataformat.yaml.YAMLGenerator
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

/**
 * Generates a JReleaser YAML config for Maven Central deployment.
 *
 * Guarded by [DefaultEasyPublishExtension.toMavenCentral]; registered only on the root project.
 * The generated file is `build/jreleaser/jreleaser.yml` and contains signing (armored, ALWAYS) and
 * `deploy.maven.mavenCentral` pointing at the global staging directory. No `release` section is generated.
 */
@CacheableTask
abstract class GenerateJreleaserConfigTask : DefaultTask() {
    @get:Input
    abstract val stagingDirectory: Property<String>

    @get:Input
    abstract val gpgPublicKey: Property<String>

    @get:Input
    abstract val gpgPrivateKey: Property<String>

    @get:Input
    abstract val gpgPassphrase: Property<String>

    @get:Input
    abstract val mavenCentralUsername: Property<String>

    @get:Input
    abstract val mavenCentralPassword: Property<String>

    @get:Input
    abstract val projectName: Property<String>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    init {
        group = "publishing"
        description = "Generates JReleaser config for Maven Central (staging at stagingDirectory)"
    }

    @TaskAction
    fun generate() {
        val file = outputFile.get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            buildYaml(
                projectName = projectName.get(),
                stagingDir = stagingDirectory.get(),
                gpgPublicKey = gpgPublicKey.get(),
                gpgPrivateKey = gpgPrivateKey.get(),
                gpgPassphrase = gpgPassphrase.get(),
                mavenCentralUsername = mavenCentralUsername.get(),
                mavenCentralPassword = mavenCentralPassword.get(),
            ),
        )
    }

    @Suppress("LongParameterList")
    internal fun buildYaml(
        projectName: String,
        stagingDir: String,
        gpgPublicKey: String,
        gpgPrivateKey: String,
        gpgPassphrase: String,
        mavenCentralUsername: String,
        mavenCentralPassword: String,
    ): String {
        val config =
            linkedMapOf(
                "project" to linkedMapOf("name" to projectName),
                "signing" to
                    linkedMapOf(
                        "active" to "ALWAYS",
                        "armored" to true,
                        "gpgPublicKey" to gpgPublicKey,
                        "gpgPrivateKey" to gpgPrivateKey,
                        "gpgPassphrase" to gpgPassphrase,
                    ),
                "deploy" to
                    linkedMapOf(
                        "maven" to
                            linkedMapOf(
                                "mavenCentral" to
                                    linkedMapOf(
                                        "active" to "ALWAYS",
                                        "url" to "https://central.sonatype.com/api/v1/publisher",
                                        "stagingRepositories" to listOf(stagingDir),
                                        "username" to mavenCentralUsername,
                                        "password" to mavenCentralPassword,
                                    ),
                            ),
                    ),
            )
        val yaml = yamlMapper.writeValueAsString(config)
        return "# Generated by EasyPublishPlugin — JReleaser config for Maven Central\n" + yaml
    }

    companion object {
        private val yamlMapper: ObjectMapper =
            ObjectMapper(
                YAMLFactory
                    .builder()
                    .enable(YAMLGenerator.Feature.MINIMIZE_QUOTES)
                    .disable(YAMLGenerator.Feature.WRITE_DOC_START_MARKER)
                    .build(),
            ).registerKotlinModule()
    }
}
