package com.mreil.easy.publish

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

/**
 * Generates a JReleaser YAML config for Maven Central deployment.
 *
 * Guarded by [DefaultEasyPublishExtension.toMavenCentral]; registered only on the root project.
 * The generated file is `build/jreleaser/jreleaser.yml` and contains signing (armored, ALWAYS) and
 * `deploy.maven.mavenCentral` pointing at the global staging directory. No `release` section is generated.
 */
@CacheableTask
abstract class GenerateJreleaserConfigTask : DefaultTask() {
    @get:Input
    abstract val stagingDirectory: Property<String>

    @get:Input
    abstract val gpgPublicKey: Property<String>

    @get:Input
    abstract val gpgPrivateKey: Property<String>

    @get:Input
    abstract val gpgPassphrase: Property<String>

    @get:Input
    abstract val mavenCentralUsername: Property<String>

    @get:Input
    abstract val mavenCentralPassword: Property<String>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    init {
        group = "publishing"
        description = "Generates JReleaser config for Maven Central (staging at stagingDirectory)"
    }

    @TaskAction
    fun generate() {
        val stagingDir = stagingDirectory.get()
        val file = outputFile.get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            buildYaml(
                stagingDir = stagingDir,
                gpgPublicKey = gpgPublicKey.get(),
                gpgPrivateKey = gpgPrivateKey.get(),
                gpgPassphrase = gpgPassphrase.get(),
                mavenCentralUsername = mavenCentralUsername.get(),
                mavenCentralPassword = mavenCentralPassword.get(),
            ),
        )
    }

    @Suppress("LongParameterList")
    private fun buildYaml(
        stagingDir: String,
        gpgPublicKey: String,
        gpgPrivateKey: String,
        gpgPassphrase: String,
        mavenCentralUsername: String,
        mavenCentralPassword: String,
    ): String =
        // Manual YAML to avoid extra dependencies; CC-compatible (inputs are Properties)
        buildString {
            appendLine("# Generated by EasyPublishPlugin — JReleaser config for Maven Central")
            appendLine("project:")
            appendLine("  name: ${project.name}")
            appendLine("signing:")
            appendLine("  active: ALWAYS")
            appendLine("  armored: true")
            appendLine("  gpgPublicKey: \"$gpgPublicKey\"")
            appendLine("  gpgPrivateKey: \"$gpgPrivateKey\"")
            appendLine("  gpgPassphrase: \"$gpgPassphrase\"")
            appendLine("deploy:")
            appendLine("  maven:")
            appendLine("    mavenCentral:")
            appendLine("      active: ALWAYS")
            appendLine("      url: https://central.sonatype.com/api/v1/publisher")
            appendLine("      stagingRepositories:")
            appendLine("        - $stagingDir")
            appendLine("      username: \"$mavenCentralUsername\"")
            appendLine("      password: \"$mavenCentralPassword\"")
        }
}
