/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/9.4.1/userguide/custom_plugins.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import org.gradle.api.artifacts.component.ModuleComponentIdentifier
import org.gradle.api.artifacts.result.ResolvedArtifactResult
import java.util.zip.ZipFile

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    alias(libs.plugins.shadow)
    alias(libs.plugins.plugin.publish)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val fixtures =
    configurations.create("fixtures") {
        isCanBeConsumed = false
        isCanBeResolved = true
    }

dependencies {
    implementation(project(":easy-plugin-core"))
    implementation(project(":easy-contributor-api"))
    // auto-collect all contributor runtime plugins (APIs are pulled transitively via their plugin)
    providers
        .provider {
            rootProject.subprojects
                .map { it.path }
                .filter { it.startsWith(":contributor-plugins:") }
                .filter { it.endsWith("-plugin") }
                .filterNot { it.endsWith("-test-plugin") }
                .sorted()
        }.get()
        .forEach { implementation(project(it)) }
    fixtures(project(":easy-test-support"))

    // The fat jar bundles only modules built by this build, so third-party dependencies must stay
    // ordinary Maven Central dependencies of the published artifact. Declaring them on the Shadow
    // `shadow` configuration keeps them out of the fat jar while still emitting them at `runtime`
    // scope in the published POM/Gradle metadata (see `shadowJar.dependencies` below).
    // Kotlin stdlib is deliberately not declared here: Gradle provides it to plugins, and it is
    // still pulled transitively by kotlinx-serialization-json. `verifyShadowPackaging` fails the
    // build if a third-party runtime dependency is not published.
    shadow(libs.commons.configuration2)
    shadow(libs.kotlinx.serialization.json)
    shadow(libs.semver4j)
}

testing {
    suites {
        // jvm-defaults registers/configures functionalTest (framework, main output, test kit and
        // plugin-under-test metadata); only the repo-specific helper projects are declared here.
        register<JvmTestSuite>("functionalTest") {
            dependencies {
                implementation(project(":easy-test-support"))
                implementation(project(":gradle-plugin-testutils"))
            }
        }
    }
}

gradlePlugin {
    website.set("https://github.com/markusreil/gradle-easy-plugin")
    vcsUrl.set("https://github.com/markusreil/gradle-easy-plugin")

    // NOTE: impl classes live in :easy-plugin-core, so :easy-plugin:jar warns
    // "implementation class ... was not found in the jar". Expected and benign: the
    // classes resolve from :easy-plugin-core on the runtime classpath. Do not move
    // declarations to core (markers would lose contributor deps) or classes here
    // (core references ProjectPlugin — dependency cycle).
    // Define the plugin
    plugins.create("easyProject") {
        id = providers.gradleProperty("plugin.project").get()
        implementationClass = "com.mreil.easy.ProjectPlugin"
        displayName = "Easy Project Plugin"
        description =
            "A Gradle plugin framework that simplifies plugin development with modular contributors and convention-based configuration"
        tags.set(listOf("kotlin", "conventions", "plugin-development", "modular"))
    }
    plugins.create("easySettings") {
        id = providers.gradleProperty("plugin.settings").get()
        implementationClass = "com.mreil.easy.SettingsPlugin"
        displayName = "Easy Settings Plugin"
        description =
            "A Gradle plugin framework that simplifies plugin development with modular contributors and convention-based configuration"
        tags.set(listOf("kotlin", "conventions", "plugin-development", "modular"))
    }
}

// The functional tests need the fixtures configuration on top of the standard plugin-under-test
// metadata; the runtimeOnly wiring itself is added by jvm-defaults.
tasks.named<PluginUnderTestMetadata>("pluginUnderTestMetadata") {
    pluginClasspath.from(fixtures)
}

// Every module built by this build shares the project group, making it the single discriminator
// between "bundled into the fat jar" (this build's modules) and "published as a Maven Central
// dependency" (third-party artifacts).
val internalGroup = project.group.toString()

tasks.named<ShadowJar>("shadowJar") {
    archiveClassifier = ""

    // Bundle only modules produced by this build: they are exactly the runtime dependencies whose
    // module group is this build's group. Third-party dependencies therefore stay out of the jar
    // and are published from the `shadow` configuration instead (see the `dependencies` block).
    // Test-only modules (`*-test-plugin` harnesses, `easy-test-support`, `gradle-plugin-testutils`)
    // are not runtime dependencies and so are never seen here; `verifyShadowPackaging` asserts it.
    dependencies {
        include { it.moduleGroup == internalGroup }
    }

    // Shadow 9.x applies duplicatesStrategy before resource transformers, so we must
    // explicitly allow duplicates for the paths the transformers merge.
    val transformedPaths = listOf("META-INF/services/**", "META-INF/*.kotlin_module")
    filesMatching(transformedPaths) {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }
    inputs.property("transformedPathsDuplicatesStrategy", "$transformedPaths=INCLUDE")

    mergeServiceFiles()
}

// Guards the packaging contract: the fat jar must contain only classes built by this build (never
// test-only modules or third-party classes), and every third-party module on the runtime classpath
// must be published via the `shadow` configuration so consumers can resolve it from Maven Central.
val verifyShadowPackaging =
    tasks.register("verifyShadowPackaging") {
        group = "verification"
        description =
            "Verifies the easy-plugin fat jar bundles only in-build modules and publishes " +
            "all third-party runtime dependencies."

        val runtimeArtifacts =
            configurations.named("runtimeClasspath").flatMap { it.incoming.artifacts.resolvedArtifacts }
        val publishedArtifacts =
            configurations.named("shadow").flatMap { it.incoming.artifacts.resolvedArtifacts }
        val shadowJarFile = tasks.named<ShadowJar>("shadowJar").flatMap { it.archiveFile }

        inputs.file(shadowJarFile).withPropertyName("shadowJar")
        inputs.files(configurations.named("runtimeClasspath")).withPropertyName("runtimeClasspath")
        inputs.files(configurations.named("shadow")).withPropertyName("publishedDependencies")

        doLast {
            fun moduleId(artifact: ResolvedArtifactResult): String? =
                (artifact.id.componentIdentifier as? ModuleComponentIdentifier)
                    ?.let { "${it.group}:${it.module}" }

            val runtimeModules = runtimeArtifacts.get().mapNotNull(::moduleId).toSet()
            val publishedModules = publishedArtifacts.get().mapNotNull(::moduleId).toSet()
            check((runtimeModules - publishedModules).isEmpty()) {
                "Third-party runtime dependencies are missing from the published artifact " +
                    "(declare them on the `shadow` configuration): ${runtimeModules - publishedModules}"
            }

            val testOnlyPrefixes =
                listOf(
                    "com/mreil/gradletest/",
                    "com/mreil/easy/fixtures/",
                    "com/mreil/easy/test/support/",
                )
            val offending =
                ZipFile(shadowJarFile.get().asFile).use { zip ->
                    zip
                        .entries()
                        .asSequence()
                        .map { it.name }
                        .filter { name ->
                            name.endsWith(".class") &&
                                (
                                    !name.startsWith("com/mreil/") ||
                                        testOnlyPrefixes.any { name.startsWith(it) } ||
                                        name.contains("TestHarnessPlugin")
                                )
                        }.toList()
                }
            check(offending.isEmpty()) {
                "The easy-plugin fat jar must bundle only modules built by this build: $offending"
            }
        }
    }

tasks.named<Task>("check") {
    // functionalTest is wired into check by jvm-defaults; only shadow-packaging verification stays repo-specific here.
    dependsOn(verifyShadowPackaging)
}
