/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/9.4.1/userguide/custom_plugins.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.detekt)
    alias(libs.plugins.shadow)
    alias(libs.plugins.plugin.publish)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val fixtures =
    configurations.create("fixtures") {
        isCanBeConsumed = false
        isCanBeResolved = true
    }

dependencies {
    implementation(project(":easy-plugin-core"))
    implementation(project(":easy-contributor-api"))
    // auto-collect all contributor runtime plugins (APIs are pulled transitively via their plugin)
    providers
        .provider {
            rootProject.subprojects
                .map { it.path }
                .filter { it.startsWith(":contributor-plugins:") }
                .filter { it.endsWith("-plugin") }
                .filterNot { it.endsWith("-test-plugin") }
                .sorted()
        }.get()
        .forEach { implementation(project(it)) }
    fixtures(project(":easy-test-support"))
}

testing {
    suites {
        // jvm-defaults registers/configures functionalTest (framework, main output, test kit and
        // plugin-under-test metadata); only the repo-specific helper projects are declared here.
        register<JvmTestSuite>("functionalTest") {
            dependencies {
                implementation(project(":easy-test-support"))
                implementation(project(":gradle-plugin-testutils"))
            }
        }
    }
}

gradlePlugin {
    website.set("https://github.com/markusreil/gradle-easy-plugin")
    vcsUrl.set("https://github.com/markusreil/gradle-easy-plugin")

    // NOTE: impl classes live in :easy-plugin-core, so :easy-plugin:jar warns
    // "implementation class ... was not found in the jar". Expected and benign: the
    // classes resolve from :easy-plugin-core on the runtime classpath. Do not move
    // declarations to core (markers would lose contributor deps) or classes here
    // (core references ProjectPlugin — dependency cycle).
    // Define the plugin
    plugins.create("easyProject") {
        id = providers.gradleProperty("plugin.project").get()
        implementationClass = "com.mreil.easy.ProjectPlugin"
        displayName = "Easy Project Plugin"
        description =
            "A Gradle plugin framework that simplifies plugin development with modular contributors and convention-based configuration"
        tags.set(listOf("kotlin", "conventions", "plugin-development", "modular"))
    }
    plugins.create("easySettings") {
        id = providers.gradleProperty("plugin.settings").get()
        implementationClass = "com.mreil.easy.SettingsPlugin"
        displayName = "Easy Settings Plugin"
        description =
            "A Gradle plugin framework that simplifies plugin development with modular contributors and convention-based configuration"
        tags.set(listOf("kotlin", "conventions", "plugin-development", "modular"))
    }
}

// The functional tests need the fixtures configuration on top of the standard plugin-under-test
// metadata; the runtimeOnly wiring itself is added by jvm-defaults.
tasks.named<PluginUnderTestMetadata>("pluginUnderTestMetadata") {
    pluginClasspath.from(fixtures)
}

detekt {
    config.setFrom(files("${rootProject.projectDir}/config/detekt/detekt.yml"))
}

tasks.named<ShadowJar>("shadowJar") {
    archiveClassifier = ""

    // Shadow 9.x applies duplicatesStrategy before resource transformers, so we must
    // explicitly allow duplicates for the paths the transformers merge.
    val transformedPaths = listOf("META-INF/services/**", "META-INF/*.kotlin_module")
    filesMatching(transformedPaths) {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }
    inputs.property("transformedPathsDuplicatesStrategy", "$transformedPaths=INCLUDE")

    mergeServiceFiles()
}

tasks.named<Task>("check") {
    // functionalTest is wired into check by jvm-defaults; only detekt stays repo-specific here.
    dependsOn("detekt")
}
