/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/9.4.1/userguide/custom_plugins.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the Java Gradle plugin development plugin to add support for developing Gradle plugins
    `java-gradle-plugin`
    jacoco

    // Apply the Kotlin JVM plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.detekt)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val fixtures by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
}

dependencies {
    implementation(project(":easy-plugin-core"))
    implementation(project(":easy-contributor-api"))
    // auto-collect all contributor runtime plugins (APIs are pulled transitively via their plugin)
    providers
        .provider {
            rootProject.subprojects
                .map { it.path }
                .filter { it.startsWith(":contributor-plugins:") }
                .filter { it.endsWith("-plugin") }
                .filterNot { it.endsWith("-test-plugin") }
                .sorted()
        }.get()
        .forEach { implementation(project(it)) }
    fixtures(project(":easy-test-support"))
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            useJUnitJupiter()
            dependencies {
                implementation(libs.assertj.core)
                implementation(libs.junit.pioneer)
            }
        }

        // Create a new test suite
        val functionalTest by registering(JvmTestSuite::class) {
            useJUnitJupiter()

            dependencies {
                // functionalTest test suite depends on the production code in tests
                implementation(project())
                implementation(project(":easy-test-support"))
                implementation(project(":gradle-plugin-testutils"))
                implementation(gradleTestKit())
                implementation(libs.assertj.core)
                implementation(libs.junit.pioneer)
            }

            targets {
                all {
                    // This test suite should run after the built-in test suite has run its tests
                    testTask.configure { shouldRunAfter(test) }
                }
            }
        }
    }
}

gradlePlugin {
    // NOTE: impl classes live in :easy-plugin-core, so :easy-plugin:jar warns
    // "implementation class ... was not found in the jar". Expected and benign: the
    // classes resolve from :easy-plugin-core on the runtime classpath. Do not move
    // declarations to core (markers would lose contributor deps) or classes here
    // (core references ProjectPlugin — dependency cycle).
    // Define the plugin
    val easyProject by plugins.creating {
        id = providers.gradleProperty("plugin.project").get()
        implementationClass = "com.mreil.easy.ProjectPlugin"
    }
    val easySettings by plugins.creating {
        id = providers.gradleProperty("plugin.settings").get()
        implementationClass = "com.mreil.easy.SettingsPlugin"
    }
}

gradlePlugin.testSourceSets.add(sourceSets["functionalTest"])

tasks.named<PluginUnderTestMetadata>("pluginUnderTestMetadata") {
    pluginClasspath.from(fixtures)
}

detekt {
    config.setFrom(files("${rootProject.projectDir}/config/detekt/detekt.yml"))
}

tasks.named<Task>("check") {
    // Include functionalTest as part of the check lifecycle
    dependsOn(testing.suites.named("functionalTest"))
    dependsOn("detekt")
    dependsOn("jacocoTestReport")
}

tasks.named<JacocoReport>("jacocoTestReport") {
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}
